import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame3.java
 *
 * Created on Jan 26, 2017, 8:57:10 AM
 */

/**
 *
 * @author IVPS
 */
public class NewJFrame3 extends javax.swing.JFrame {Connection con=null;
Statement stm=null;
ResultSet rs=null;
Connection con1=null;
Statement stm1=null;
ResultSet rs1=null;
    /** Creates new form NewJFrame3 */
    public NewJFrame3() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 50, 310, 40);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 250, 310, 20);

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 220, 310, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 100, 310, 110);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 350, 100, 23);

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(190, 280, 310, 20);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 310, 310, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("BILL AMOUNT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 260, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 60, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 70, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Car Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("VAT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 70, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Total Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 100, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("H:\\Images\\audi a6.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 70, 550, 320);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 180, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed




    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a="",b="";

 try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/b","root","deepali");
    stm=con.createStatement();
    String q="select Name,Address from signup where Name='"+gv.t+"';";

    rs=stm.executeQuery(q);
    while(rs.next())
    { a=rs.getString("Name");
     b=rs.getString("Address");

    }


     jTextField1.setText(a);
             jTextArea1.setText(b);
    }
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());

}


int f;
float c,d;
f=Integer.parseInt(jTextField2.getText());

c=(f*14)/100;
jTextField4.setText(""+c);
 d=f+c;
 jTextField5.setText(""+d);
gv.a=jTextField1.getText();
gv.b=jTextArea1.getText();
gv.c=jTextField3.getText();
gv.d=jTextField5.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String a="",b="";

 try{
    Class.forName("java.sql.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost/b","root","deepali");
    stm=con.createStatement();
    String q="select Name,Address from signup where Name='"+gv.t+"';";

    rs=stm.executeQuery(q);
    while(rs.next())
    { a=rs.getString("Name");
     b=rs.getString("Address");

    }


     jTextField1.setText(a);
             jTextArea1.setText(b);
    }
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());

}
 String a1="",b1="";
 try{
    Class.forName("java.sql.Driver");
    con1=DriverManager.getConnection("jdbc:mysql://localhost/b","root","deepali");
    stm1=con1.createStatement();
    String q="select CarName,price from  "+NewClass.c1+" where CarName='"+NewClass.c2+"';";

    rs1=stm1.executeQuery(q);
    while(rs1.next())
    { a1=rs1.getString("carName");
     b1=rs1.getString("price");

    }


     jTextField3.setText(a1);
             jTextField2.setText(b1);
    }
catch(Exception e)
{JOptionPane.showMessageDialog(null,e.getMessage());

}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
    Class.forName("java.sql.Driver");

   con=DriverManager.getConnection("jdbc:mysql://localhost/b","root","deepali");
       stm=con.createStatement();
       String q="Insert into customer details values('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jTextArea1.getText()+"',"+jTextField3.getText()+",'"+jPasswordField1.getPassword()+"');";
stm.executeUpdate(q);

   }

    catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    String a=jTextField1.getText();
gv.t=a;
    new NewJFrame().setVisible(true);
     this.dispose();

        





// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
